export const completedAuditFixture = {
  schemaVersion: 1,
  auditId: "audit-1",
  requestId: "request-1",
  profile: "application_remnants",
  state: "completed",
  stateVersion: 4,
  startedAt: "2026-07-17T00:00:00.000Z",
  finishedAt: "2026-07-17T00:01:00.000Z",
  cancelRequestedAt: null,
  capabilities: {
    supportedSources: ["application_inventory"],
    unavailableSources: [],
  },
  coverage: {
    checkedSourceCount: 1,
    skippedSourceCount: 0,
  },
  warnings: [],
  revision: 1,
} as const;

export const findingFixture = {
  model: {
    findingId: "finding-1",
    displayName: "Синтетический кэш",
    category: "cache",
    supportLevel: "candidate",
    logicalSize: 84,
    physicalSize: 42,
    label: "orphaned",
    confidence: "high",
    risk: "low",
    allowedActions: ["inspect", "reveal", "exclude", "prepare_move"],
    safeMetadata: {
      format: "plist",
      parseStatus: "parsed",
      byteLength: 128,
      modifiedAt: "2026-07-17T00:00:00.000Z",
      sensitivityFlags: [],
    },
    blockingReasons: [],
  },
  widget: {
    canonicalPath: "/synthetic/Library/Caches/org.example.old",
    componentDisplayName: "Synthetic App",
    findingFacts: {
      lastObservedAt: "2026-07-17T00:00:00.000Z",
      temporalKind: "stale",
      mainBundleState: "absent",
      activityState: "absent",
      openFileState: "absent",
      startupKinds: [],
      targetExecutableState: "absent",
      receiptState: "unknown",
      dependencyState: "absent",
      sensitivityFlags: [],
      recommendedRemovalMethod: "quarantine",
      blockingReasons: [],
    },
    reclaimEstimate: {
      estimatedPhysicalBytes: 42,
      confidence: "high",
      basis: "observed_physical_size",
      limitations: ["snapshot_estimate"],
      observedAt: "2026-07-17T00:00:00.000Z",
    },
    evidence: [],
  },
} as const;
